### ISSUE TITLE
Improvements and known issues - Plot v1

### ISSUE THREAD

**Issue by agouy** [tercen/plot_operator#1]
- [x] x axis name in heatmap is ignored
- [x] sometimes different colors for different layers
- [x] settings for text element sizes
- [x] support for error bars
- [x] support for labels: behaviour to be defined
- [x] default plot size
- [x] Support for space in factor names in colors
- [x] Add a setting to rotate Axis labels (+ label_wrap() capability)
- [x] read custom palette range
- [x] row and column indices are being displayed (heatmaps) -> should use labels
- [x] No color legend in heatmap
- [x] Support for h and v lines
- [x] Handle absence of colors (use crosstab colors instead of black?)
- [x] heatmap color legend
- [x] setting to define the legend title
- [x] when facetting with [facet_grid()](https://ggplot2.tidyverse.org/reference/facet_grid.html) set parameter switch = "y", so that the labels appear on the left
- [x] Support for text labels
- [x] Size defined in crosstab influences size of element in plot

**Comment by agouy** [comment]
- Support for derived factors in colors

**Comment by agouy** [comment]
* Rotate axis setting

**Comment by makostadima** [comment]
@agouy Can I also add the option to define the legend.title which at the moment is just 'Legend'?

![image](https://github.com/tercen/plot_operator/assets/1746464/f5d7c042-dab4-4fa9-935c-723df5e7b748)

**Comment by makostadima** [comment]
@agouy version 0.0.3 throws an error when there are multiple layers but no color groups defined. See [here](https://tercen.com/tercen/w/c400a75f13edb36d04ca4bc484b26d8c/ds/eb755282-3279-4326-89bd-e84f422dd558).

This used to work with earlier versions as the colors were by default grey.

**Comment by makostadima** [comment]
Current version 0.0.12. @agouy I'm putting together the list of improvements I've already mentioned to you on slack:

- [x] heatmap color legend
- [x] setting to define the legend title
- [x] when facetting with [facet_grid()](https://ggplot2.tidyverse.org/reference/facet_grid.html) set parameter switch = "y", so that the labels appear on the left

**Comment by agouy** [comment]
0.1.0 includes all those features
