### ISSUE TITLE
Error message on Plot Operator.

### ISSUE THREAD

**Issue by martin1english** [tercen/plot_operator#3]
Hi,
I have configured a plot operator here.
[https://tercen.com/tercenTest/w/0426e43fae546a36d7cae002c11e64e3/ds/62a03bc6-ccfe-44a8-9bfa-f622593a55d7](url)

I get this error message.

![image](https://github.com/tercen/plot_operator/assets/64135638/20d75ebb-83da-4d77-addc-545d3a71aa6b)

**Comment by agouy** [comment]
The categorical palette set in the crosstab was not recognised by the operator because of some weird behaviour observed in this case. This is fixed in 0.1.0
