### ISSUE TITLE
Error when factor names contains spaces

### ISSUE THREAD

**Issue by makostadima** [tercen/plot_operator#5]
@agouy this is an issue that PamGene is facing.

Here is the step where the error is thrown:

https://bionavigator.pamgene.com/Test_NewTemplates/w/6ccbdf915acee80757a2d4a2f8c29b78/ds/8fb1064f-7adb-4e46-beaf-15f69ab456fd

And here is the error message:

![image](https://github.com/tercen/plot_operator/assets/1746464/730d4cf8-b0a3-46d5-9d98-253a3613c724)

**Comment by agouy** [comment]
@makostadima Could you please try 0.1.7 and confirm whether the issue is fixed?

**Comment by makostadima** [comment]
I can confirm that the issue has been fixed.
